services:
  app:
    build: .
    tty: true
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
  db:
    build:
      context: "."
      dockerfile: "db.Dockerfile"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scroll_cube
    volumes:
      - scroll-cube-score:/var/lib/postgresql/data
volumes:
  scroll-cube-score:
    external: true